### PR TITLE
Rename sub modules.

### LINKED ISSUE #140: Rename sub projects of core project (wrt to dropwizard)
I don't think that the `dropwizard-app` and `dropwizard-api` designations are particularly valuable and locks us in to using dropwizard as a dependency/frameworks.  Sub projects of `app` (service?) and `api` seem cleaner

### PR DESCRIPTION
**Pull request by jshort**
Resolves #140

### CODE REVIEW

**Comment by carltonwhitehead** [comment]
I made some conflicts when I merged my ConerCoreService elimination PR. I'll fix this one and push a commit in a little bit.

**Comment by jshort** [comment]
I'll update the PR but are you ok with the change?

**Comment by carltonwhitehead** [comment]
Yeah, I like it. For the merge conflicts, it should just be a matter of keeping the files I changed and moving them into the updated path

**Comment by carltonwhitehead** [comment]
It sounds like you will be fixing the merge. I'd be happy to take care of it if you don't think you'll get to it in the next couple days.

**Comment by jshort** [comment]
@carltonwhitehead sorry, on it now.  Updating Readme since it's wrong now :).

**Pull request merged**
